### PR TITLE
Extended to include options.source param, added unit tests

### PR DESCRIPTION
**Pull request by jaetask**
Hi @sinabakh, Thanks for creating this library, it's exactly what I was looking for. I have extended it to allow a source input to transform the values instead of always creating a new object.

This allows a source object, to be extended by merging transformed values from the passed object.

I hope you don't mind, I updated the project files a little and added jest test coverage to ensure I hadn't broken the original strict option as well as coverage for the new source option.

Regards
Jae

### CODE REVIEW

**Comment by sinabakh** [comment]
Hi @jaetask, it's good to hear this library has other users other than my old personal projects.

The `source` option is awesome and also thanks for all of your changes, cleanups, updates, and unit tests. The whole package is more professional now 👍.

Regarding the `source` option, I have a question. It seems if the source has a field and the field is defined in the transformer too, the source field will be overridden. Is it the expected behavior? I personally think that's what should happen but just wanted to check it with you.

Thanks
Sina

**Comment by jaetask** [comment]
Yeah, that's exactly the idea. 

The transformer overrides any fields/values in the source. This saves us having to do a merge after transform with the source and the transformer output.

Jae.

**Comment by sinabakh** [comment]
Nice, so everything's ok. Thank you again.

**Comment by jaetask** [comment]
Awesome. Any chance you can publish the updates to npm?

**Comment by sinabakh** [comment]
@jaetask Sorry I was off for two days. I will publish it ASAP.

**Pull request merged**
